/* Autogenerated code - do not modify */
#include <assert.h>
#include <mono/jit/jit.h>
#include <mono/metadata/assembly.h>
#include <mono/metadata/debug-helpers.h>
#define DEFINE_MONKEY_INTERNALS
#define DECLARE_BINDING
#include "monkey.h"
MonoMethod *pMsrMatrix_New;
void MsrMatrix_New(int* _ref,int* LocalNumberOfRows,int* NoOfColumns,int* _RowsPerBlock,int* _ColPerBlock,int* ierr){
void* args[6];
args [0] = _ref;
args [1] = LocalNumberOfRows;
args [2] = NoOfColumns;
args [3] = _RowsPerBlock;
args [4] = _ColPerBlock;
args [5] = ierr;
mono_runtime_invoke (pMsrMatrix_New, NULL, args, NULL);
}
void msrmatrix_new(int* _ref,int* LocalNumberOfRows,int* NoOfColumns,int* _RowsPerBlock,int* _ColPerBlock,int* ierr){MsrMatrix_New(_ref,LocalNumberOfRows,NoOfColumns,_RowsPerBlock,_ColPerBlock,ierr);}
void MSRMATRIX_NEW(int* _ref,int* LocalNumberOfRows,int* NoOfColumns,int* _RowsPerBlock,int* _ColPerBlock,int* ierr){MsrMatrix_New(_ref,LocalNumberOfRows,NoOfColumns,_RowsPerBlock,_ColPerBlock,ierr);}
void msrmatrix_new_(int* _ref,int* LocalNumberOfRows,int* NoOfColumns,int* _RowsPerBlock,int* _ColPerBlock,int* ierr){MsrMatrix_New(_ref,LocalNumberOfRows,NoOfColumns,_RowsPerBlock,_ColPerBlock,ierr);}
void MSRMATRIX_NEW_(int* _ref,int* LocalNumberOfRows,int* NoOfColumns,int* _RowsPerBlock,int* _ColPerBlock,int* ierr){MsrMatrix_New(_ref,LocalNumberOfRows,NoOfColumns,_RowsPerBlock,_ColPerBlock,ierr);}
void _msrmatrix_new(int* _ref,int* LocalNumberOfRows,int* NoOfColumns,int* _RowsPerBlock,int* _ColPerBlock,int* ierr){MsrMatrix_New(_ref,LocalNumberOfRows,NoOfColumns,_RowsPerBlock,_ColPerBlock,ierr);}
void _MSRMATRIX_NEW(int* _ref,int* LocalNumberOfRows,int* NoOfColumns,int* _RowsPerBlock,int* _ColPerBlock,int* ierr){MsrMatrix_New(_ref,LocalNumberOfRows,NoOfColumns,_RowsPerBlock,_ColPerBlock,ierr);}
void _MsrMatrix_New(int* _ref,int* LocalNumberOfRows,int* NoOfColumns,int* _RowsPerBlock,int* _ColPerBlock,int* ierr){MsrMatrix_New(_ref,LocalNumberOfRows,NoOfColumns,_RowsPerBlock,_ColPerBlock,ierr);}
void MsrMatrix_New_(int* _ref,int* LocalNumberOfRows,int* NoOfColumns,int* _RowsPerBlock,int* _ColPerBlock,int* ierr){MsrMatrix_New(_ref,LocalNumberOfRows,NoOfColumns,_RowsPerBlock,_ColPerBlock,ierr);}
MonoMethod *pIMutableMatrix_SetEntry;
void IMutableMatrix_SetEntry(int* _ref,int* i,int* j,double* val,int* ierr){
void* args[5];
args [0] = _ref;
args [1] = i;
args [2] = j;
args [3] = val;
args [4] = ierr;
mono_runtime_invoke (pIMutableMatrix_SetEntry, NULL, args, NULL);
}
void imutablematrix_setentry(int* _ref,int* i,int* j,double* val,int* ierr){IMutableMatrix_SetEntry(_ref,i,j,val,ierr);}
void IMUTABLEMATRIX_SETENTRY(int* _ref,int* i,int* j,double* val,int* ierr){IMutableMatrix_SetEntry(_ref,i,j,val,ierr);}
void imutablematrix_setentry_(int* _ref,int* i,int* j,double* val,int* ierr){IMutableMatrix_SetEntry(_ref,i,j,val,ierr);}
void IMUTABLEMATRIX_SETENTRY_(int* _ref,int* i,int* j,double* val,int* ierr){IMutableMatrix_SetEntry(_ref,i,j,val,ierr);}
void _imutablematrix_setentry(int* _ref,int* i,int* j,double* val,int* ierr){IMutableMatrix_SetEntry(_ref,i,j,val,ierr);}
void _IMUTABLEMATRIX_SETENTRY(int* _ref,int* i,int* j,double* val,int* ierr){IMutableMatrix_SetEntry(_ref,i,j,val,ierr);}
void _IMutableMatrix_SetEntry(int* _ref,int* i,int* j,double* val,int* ierr){IMutableMatrix_SetEntry(_ref,i,j,val,ierr);}
void IMutableMatrix_SetEntry_(int* _ref,int* i,int* j,double* val,int* ierr){IMutableMatrix_SetEntry(_ref,i,j,val,ierr);}
MonoMethod *pCommon_ReleaseObject;
void Common_ReleaseObject(int* _ref,int* ierr){
void* args[2];
args [0] = _ref;
args [1] = ierr;
mono_runtime_invoke (pCommon_ReleaseObject, NULL, args, NULL);
}
void common_releaseobject(int* _ref,int* ierr){Common_ReleaseObject(_ref,ierr);}
void COMMON_RELEASEOBJECT(int* _ref,int* ierr){Common_ReleaseObject(_ref,ierr);}
void common_releaseobject_(int* _ref,int* ierr){Common_ReleaseObject(_ref,ierr);}
void COMMON_RELEASEOBJECT_(int* _ref,int* ierr){Common_ReleaseObject(_ref,ierr);}
void _common_releaseobject(int* _ref,int* ierr){Common_ReleaseObject(_ref,ierr);}
void _COMMON_RELEASEOBJECT(int* _ref,int* ierr){Common_ReleaseObject(_ref,ierr);}
void _Common_ReleaseObject(int* _ref,int* ierr){Common_ReleaseObject(_ref,ierr);}
void Common_ReleaseObject_(int* _ref,int* ierr){Common_ReleaseObject(_ref,ierr);}
MonoMethod *pCommon_Test;
void Common_Test(int* dummy,int* ierr){
void* args[2];
args [0] = dummy;
args [1] = ierr;
mono_runtime_invoke (pCommon_Test, NULL, args, NULL);
}
void common_test(int* dummy,int* ierr){Common_Test(dummy,ierr);}
void COMMON_TEST(int* dummy,int* ierr){Common_Test(dummy,ierr);}
void common_test_(int* dummy,int* ierr){Common_Test(dummy,ierr);}
void COMMON_TEST_(int* dummy,int* ierr){Common_Test(dummy,ierr);}
void _common_test(int* dummy,int* ierr){Common_Test(dummy,ierr);}
void _COMMON_TEST(int* dummy,int* ierr){Common_Test(dummy,ierr);}
void _Common_Test(int* dummy,int* ierr){Common_Test(dummy,ierr);}
void Common_Test_(int* dummy,int* ierr){Common_Test(dummy,ierr);}
MonoMethod *pCommon_ilPSPInitialize;
void Common_ilPSPInitialize(){
void* args[0];
mono_runtime_invoke (pCommon_ilPSPInitialize, NULL, args, NULL);
}
void common_ilpspinitialize(){Common_ilPSPInitialize();}
void COMMON_ILPSPINITIALIZE(){Common_ilPSPInitialize();}
void common_ilpspinitialize_(){Common_ilPSPInitialize();}
void COMMON_ILPSPINITIALIZE_(){Common_ilPSPInitialize();}
void _common_ilpspinitialize(){Common_ilPSPInitialize();}
void _COMMON_ILPSPINITIALIZE(){Common_ilPSPInitialize();}
void _Common_ilPSPInitialize(){Common_ilPSPInitialize();}
void Common_ilPSPInitialize_(){Common_ilPSPInitialize();}
MonoMethod *pCommon_ilPSPFinalize;
void Common_ilPSPFinalize(){
void* args[0];
mono_runtime_invoke (pCommon_ilPSPFinalize, NULL, args, NULL);
}
void common_ilpspfinalize(){Common_ilPSPFinalize();}
void COMMON_ILPSPFINALIZE(){Common_ilPSPFinalize();}
void common_ilpspfinalize_(){Common_ilPSPFinalize();}
void COMMON_ILPSPFINALIZE_(){Common_ilPSPFinalize();}
void _common_ilpspfinalize(){Common_ilPSPFinalize();}
void _COMMON_ILPSPFINALIZE(){Common_ilPSPFinalize();}
void _Common_ilPSPFinalize(){Common_ilPSPFinalize();}
void Common_ilPSPFinalize_(){Common_ilPSPFinalize();}
MonoMethod *pIMutableMatrixEx_SaveToTextFileSparse;
void IMutableMatrixEx_SaveToTextFileSparse(int* _ref,char* path,int* ierr){
void* args[3];
args [0] = _ref;
args [1] = path;
args [2] = ierr;
mono_runtime_invoke (pIMutableMatrixEx_SaveToTextFileSparse, NULL, args, NULL);
}
void imutablematrixex_savetotextfilesparse(int* _ref,char* path,int* ierr){IMutableMatrixEx_SaveToTextFileSparse(_ref,path,ierr);}
void IMUTABLEMATRIXEX_SAVETOTEXTFILESPARSE(int* _ref,char* path,int* ierr){IMutableMatrixEx_SaveToTextFileSparse(_ref,path,ierr);}
void imutablematrixex_savetotextfilesparse_(int* _ref,char* path,int* ierr){IMutableMatrixEx_SaveToTextFileSparse(_ref,path,ierr);}
void IMUTABLEMATRIXEX_SAVETOTEXTFILESPARSE_(int* _ref,char* path,int* ierr){IMutableMatrixEx_SaveToTextFileSparse(_ref,path,ierr);}
void _imutablematrixex_savetotextfilesparse(int* _ref,char* path,int* ierr){IMutableMatrixEx_SaveToTextFileSparse(_ref,path,ierr);}
void _IMUTABLEMATRIXEX_SAVETOTEXTFILESPARSE(int* _ref,char* path,int* ierr){IMutableMatrixEx_SaveToTextFileSparse(_ref,path,ierr);}
void _IMutableMatrixEx_SaveToTextFileSparse(int* _ref,char* path,int* ierr){IMutableMatrixEx_SaveToTextFileSparse(_ref,path,ierr);}
void IMutableMatrixEx_SaveToTextFileSparse_(int* _ref,char* path,int* ierr){IMutableMatrixEx_SaveToTextFileSparse(_ref,path,ierr);}
MonoMethod *pIMutableMatrixEx_SaveToTextFileSparseF;
void IMutableMatrixEx_SaveToTextFileSparseF(int* _ref,char* termchar,char* path,int* ierr){
void* args[4];
args [0] = _ref;
args [1] = termchar;
args [2] = path;
args [3] = ierr;
mono_runtime_invoke (pIMutableMatrixEx_SaveToTextFileSparseF, NULL, args, NULL);
}
void imutablematrixex_savetotextfilesparsef(int* _ref,char* termchar,char* path,int* ierr){IMutableMatrixEx_SaveToTextFileSparseF(_ref,termchar,path,ierr);}
void IMUTABLEMATRIXEX_SAVETOTEXTFILESPARSEF(int* _ref,char* termchar,char* path,int* ierr){IMutableMatrixEx_SaveToTextFileSparseF(_ref,termchar,path,ierr);}
void imutablematrixex_savetotextfilesparsef_(int* _ref,char* termchar,char* path,int* ierr){IMutableMatrixEx_SaveToTextFileSparseF(_ref,termchar,path,ierr);}
void IMUTABLEMATRIXEX_SAVETOTEXTFILESPARSEF_(int* _ref,char* termchar,char* path,int* ierr){IMutableMatrixEx_SaveToTextFileSparseF(_ref,termchar,path,ierr);}
void _imutablematrixex_savetotextfilesparsef(int* _ref,char* termchar,char* path,int* ierr){IMutableMatrixEx_SaveToTextFileSparseF(_ref,termchar,path,ierr);}
void _IMUTABLEMATRIXEX_SAVETOTEXTFILESPARSEF(int* _ref,char* termchar,char* path,int* ierr){IMutableMatrixEx_SaveToTextFileSparseF(_ref,termchar,path,ierr);}
void _IMutableMatrixEx_SaveToTextFileSparseF(int* _ref,char* termchar,char* path,int* ierr){IMutableMatrixEx_SaveToTextFileSparseF(_ref,termchar,path,ierr);}
void IMutableMatrixEx_SaveToTextFileSparseF_(int* _ref,char* termchar,char* path,int* ierr){IMutableMatrixEx_SaveToTextFileSparseF(_ref,termchar,path,ierr);}
MonoMethod *pISparseMatrix_GetI0;
void ISparseMatrix_GetI0(int* _ref,int* i0,int* ierr){
void* args[3];
args [0] = _ref;
args [1] = i0;
args [2] = ierr;
mono_runtime_invoke (pISparseMatrix_GetI0, NULL, args, NULL);
}
void isparsematrix_geti0(int* _ref,int* i0,int* ierr){ISparseMatrix_GetI0(_ref,i0,ierr);}
void ISPARSEMATRIX_GETI0(int* _ref,int* i0,int* ierr){ISparseMatrix_GetI0(_ref,i0,ierr);}
void isparsematrix_geti0_(int* _ref,int* i0,int* ierr){ISparseMatrix_GetI0(_ref,i0,ierr);}
void ISPARSEMATRIX_GETI0_(int* _ref,int* i0,int* ierr){ISparseMatrix_GetI0(_ref,i0,ierr);}
void _isparsematrix_geti0(int* _ref,int* i0,int* ierr){ISparseMatrix_GetI0(_ref,i0,ierr);}
void _ISPARSEMATRIX_GETI0(int* _ref,int* i0,int* ierr){ISparseMatrix_GetI0(_ref,i0,ierr);}
void _ISparseMatrix_GetI0(int* _ref,int* i0,int* ierr){ISparseMatrix_GetI0(_ref,i0,ierr);}
void ISparseMatrix_GetI0_(int* _ref,int* i0,int* ierr){ISparseMatrix_GetI0(_ref,i0,ierr);}
MonoMethod *pISparseMatrix_GetLocLen;
void ISparseMatrix_GetLocLen(int* _ref,int* LocLen,int* ierr){
void* args[3];
args [0] = _ref;
args [1] = LocLen;
args [2] = ierr;
mono_runtime_invoke (pISparseMatrix_GetLocLen, NULL, args, NULL);
}
void isparsematrix_getloclen(int* _ref,int* LocLen,int* ierr){ISparseMatrix_GetLocLen(_ref,LocLen,ierr);}
void ISPARSEMATRIX_GETLOCLEN(int* _ref,int* LocLen,int* ierr){ISparseMatrix_GetLocLen(_ref,LocLen,ierr);}
void isparsematrix_getloclen_(int* _ref,int* LocLen,int* ierr){ISparseMatrix_GetLocLen(_ref,LocLen,ierr);}
void ISPARSEMATRIX_GETLOCLEN_(int* _ref,int* LocLen,int* ierr){ISparseMatrix_GetLocLen(_ref,LocLen,ierr);}
void _isparsematrix_getloclen(int* _ref,int* LocLen,int* ierr){ISparseMatrix_GetLocLen(_ref,LocLen,ierr);}
void _ISPARSEMATRIX_GETLOCLEN(int* _ref,int* LocLen,int* ierr){ISparseMatrix_GetLocLen(_ref,LocLen,ierr);}
void _ISparseMatrix_GetLocLen(int* _ref,int* LocLen,int* ierr){ISparseMatrix_GetLocLen(_ref,LocLen,ierr);}
void ISparseMatrix_GetLocLen_(int* _ref,int* LocLen,int* ierr){ISparseMatrix_GetLocLen(_ref,LocLen,ierr);}
MonoMethod *pISparseMatrix_GetRowPart;
void ISparseMatrix_GetRowPart(int* MtxRef,int* PartRef,int* ierr){
void* args[3];
args [0] = MtxRef;
args [1] = PartRef;
args [2] = ierr;
mono_runtime_invoke (pISparseMatrix_GetRowPart, NULL, args, NULL);
}
void isparsematrix_getrowpart(int* MtxRef,int* PartRef,int* ierr){ISparseMatrix_GetRowPart(MtxRef,PartRef,ierr);}
void ISPARSEMATRIX_GETROWPART(int* MtxRef,int* PartRef,int* ierr){ISparseMatrix_GetRowPart(MtxRef,PartRef,ierr);}
void isparsematrix_getrowpart_(int* MtxRef,int* PartRef,int* ierr){ISparseMatrix_GetRowPart(MtxRef,PartRef,ierr);}
void ISPARSEMATRIX_GETROWPART_(int* MtxRef,int* PartRef,int* ierr){ISparseMatrix_GetRowPart(MtxRef,PartRef,ierr);}
void _isparsematrix_getrowpart(int* MtxRef,int* PartRef,int* ierr){ISparseMatrix_GetRowPart(MtxRef,PartRef,ierr);}
void _ISPARSEMATRIX_GETROWPART(int* MtxRef,int* PartRef,int* ierr){ISparseMatrix_GetRowPart(MtxRef,PartRef,ierr);}
void _ISparseMatrix_GetRowPart(int* MtxRef,int* PartRef,int* ierr){ISparseMatrix_GetRowPart(MtxRef,PartRef,ierr);}
void ISparseMatrix_GetRowPart_(int* MtxRef,int* PartRef,int* ierr){ISparseMatrix_GetRowPart(MtxRef,PartRef,ierr);}
MonoMethod *pISparseSolver_FromXML;
void ISparseSolver_FromXML(int* ref_,char* xmlcode,int* ierr){
void* args[3];
args [0] = ref_;
args [1] = xmlcode;
args [2] = ierr;
mono_runtime_invoke (pISparseSolver_FromXML, NULL, args, NULL);
}
void isparsesolver_fromxml(int* ref_,char* xmlcode,int* ierr){ISparseSolver_FromXML(ref_,xmlcode,ierr);}
void ISPARSESOLVER_FROMXML(int* ref_,char* xmlcode,int* ierr){ISparseSolver_FromXML(ref_,xmlcode,ierr);}
void isparsesolver_fromxml_(int* ref_,char* xmlcode,int* ierr){ISparseSolver_FromXML(ref_,xmlcode,ierr);}
void ISPARSESOLVER_FROMXML_(int* ref_,char* xmlcode,int* ierr){ISparseSolver_FromXML(ref_,xmlcode,ierr);}
void _isparsesolver_fromxml(int* ref_,char* xmlcode,int* ierr){ISparseSolver_FromXML(ref_,xmlcode,ierr);}
void _ISPARSESOLVER_FROMXML(int* ref_,char* xmlcode,int* ierr){ISparseSolver_FromXML(ref_,xmlcode,ierr);}
void _ISparseSolver_FromXML(int* ref_,char* xmlcode,int* ierr){ISparseSolver_FromXML(ref_,xmlcode,ierr);}
void ISparseSolver_FromXML_(int* ref_,char* xmlcode,int* ierr){ISparseSolver_FromXML(ref_,xmlcode,ierr);}
MonoMethod *pISparseSolver_FromXMLBegin;
void ISparseSolver_FromXMLBegin(char* lineTerm,int* ierr){
void* args[2];
args [0] = lineTerm;
args [1] = ierr;
mono_runtime_invoke (pISparseSolver_FromXMLBegin, NULL, args, NULL);
}
void isparsesolver_fromxmlbegin(char* lineTerm,int* ierr){ISparseSolver_FromXMLBegin(lineTerm,ierr);}
void ISPARSESOLVER_FROMXMLBEGIN(char* lineTerm,int* ierr){ISparseSolver_FromXMLBegin(lineTerm,ierr);}
void isparsesolver_fromxmlbegin_(char* lineTerm,int* ierr){ISparseSolver_FromXMLBegin(lineTerm,ierr);}
void ISPARSESOLVER_FROMXMLBEGIN_(char* lineTerm,int* ierr){ISparseSolver_FromXMLBegin(lineTerm,ierr);}
void _isparsesolver_fromxmlbegin(char* lineTerm,int* ierr){ISparseSolver_FromXMLBegin(lineTerm,ierr);}
void _ISPARSESOLVER_FROMXMLBEGIN(char* lineTerm,int* ierr){ISparseSolver_FromXMLBegin(lineTerm,ierr);}
void _ISparseSolver_FromXMLBegin(char* lineTerm,int* ierr){ISparseSolver_FromXMLBegin(lineTerm,ierr);}
void ISparseSolver_FromXMLBegin_(char* lineTerm,int* ierr){ISparseSolver_FromXMLBegin(lineTerm,ierr);}
MonoMethod *pISparseSolver_FromXMLSubmit;
void ISparseSolver_FromXMLSubmit(char* line,int* ierr){
void* args[2];
args [0] = line;
args [1] = ierr;
mono_runtime_invoke (pISparseSolver_FromXMLSubmit, NULL, args, NULL);
}
void isparsesolver_fromxmlsubmit(char* line,int* ierr){ISparseSolver_FromXMLSubmit(line,ierr);}
void ISPARSESOLVER_FROMXMLSUBMIT(char* line,int* ierr){ISparseSolver_FromXMLSubmit(line,ierr);}
void isparsesolver_fromxmlsubmit_(char* line,int* ierr){ISparseSolver_FromXMLSubmit(line,ierr);}
void ISPARSESOLVER_FROMXMLSUBMIT_(char* line,int* ierr){ISparseSolver_FromXMLSubmit(line,ierr);}
void _isparsesolver_fromxmlsubmit(char* line,int* ierr){ISparseSolver_FromXMLSubmit(line,ierr);}
void _ISPARSESOLVER_FROMXMLSUBMIT(char* line,int* ierr){ISparseSolver_FromXMLSubmit(line,ierr);}
void _ISparseSolver_FromXMLSubmit(char* line,int* ierr){ISparseSolver_FromXMLSubmit(line,ierr);}
void ISparseSolver_FromXMLSubmit_(char* line,int* ierr){ISparseSolver_FromXMLSubmit(line,ierr);}
MonoMethod *pISparseSolver_FromXMLEnd;
void ISparseSolver_FromXMLEnd(int* SolverRef,int* ierr){
void* args[2];
args [0] = SolverRef;
args [1] = ierr;
mono_runtime_invoke (pISparseSolver_FromXMLEnd, NULL, args, NULL);
}
void isparsesolver_fromxmlend(int* SolverRef,int* ierr){ISparseSolver_FromXMLEnd(SolverRef,ierr);}
void ISPARSESOLVER_FROMXMLEND(int* SolverRef,int* ierr){ISparseSolver_FromXMLEnd(SolverRef,ierr);}
void isparsesolver_fromxmlend_(int* SolverRef,int* ierr){ISparseSolver_FromXMLEnd(SolverRef,ierr);}
void ISPARSESOLVER_FROMXMLEND_(int* SolverRef,int* ierr){ISparseSolver_FromXMLEnd(SolverRef,ierr);}
void _isparsesolver_fromxmlend(int* SolverRef,int* ierr){ISparseSolver_FromXMLEnd(SolverRef,ierr);}
void _ISPARSESOLVER_FROMXMLEND(int* SolverRef,int* ierr){ISparseSolver_FromXMLEnd(SolverRef,ierr);}
void _ISparseSolver_FromXMLEnd(int* SolverRef,int* ierr){ISparseSolver_FromXMLEnd(SolverRef,ierr);}
void ISparseSolver_FromXMLEnd_(int* SolverRef,int* ierr){ISparseSolver_FromXMLEnd(SolverRef,ierr);}
MonoMethod *pISparseSolver_FromXMLFileF;
void ISparseSolver_FromXMLFileF(int* SolverRef,char* termChar,char* File,char* solvername,int* ierr){
void* args[5];
args [0] = SolverRef;
args [1] = termChar;
args [2] = File;
args [3] = solvername;
args [4] = ierr;
mono_runtime_invoke (pISparseSolver_FromXMLFileF, NULL, args, NULL);
}
void isparsesolver_fromxmlfilef(int* SolverRef,char* termChar,char* File,char* solvername,int* ierr){ISparseSolver_FromXMLFileF(SolverRef,termChar,File,solvername,ierr);}
void ISPARSESOLVER_FROMXMLFILEF(int* SolverRef,char* termChar,char* File,char* solvername,int* ierr){ISparseSolver_FromXMLFileF(SolverRef,termChar,File,solvername,ierr);}
void isparsesolver_fromxmlfilef_(int* SolverRef,char* termChar,char* File,char* solvername,int* ierr){ISparseSolver_FromXMLFileF(SolverRef,termChar,File,solvername,ierr);}
void ISPARSESOLVER_FROMXMLFILEF_(int* SolverRef,char* termChar,char* File,char* solvername,int* ierr){ISparseSolver_FromXMLFileF(SolverRef,termChar,File,solvername,ierr);}
void _isparsesolver_fromxmlfilef(int* SolverRef,char* termChar,char* File,char* solvername,int* ierr){ISparseSolver_FromXMLFileF(SolverRef,termChar,File,solvername,ierr);}
void _ISPARSESOLVER_FROMXMLFILEF(int* SolverRef,char* termChar,char* File,char* solvername,int* ierr){ISparseSolver_FromXMLFileF(SolverRef,termChar,File,solvername,ierr);}
void _ISparseSolver_FromXMLFileF(int* SolverRef,char* termChar,char* File,char* solvername,int* ierr){ISparseSolver_FromXMLFileF(SolverRef,termChar,File,solvername,ierr);}
void ISparseSolver_FromXMLFileF_(int* SolverRef,char* termChar,char* File,char* solvername,int* ierr){ISparseSolver_FromXMLFileF(SolverRef,termChar,File,solvername,ierr);}
MonoMethod *pISparseSolver_FromXMLFile;
void ISparseSolver_FromXMLFile(int* SolverRef,char* File,char* solvername,int* ierr){
void* args[4];
args [0] = SolverRef;
args [1] = File;
args [2] = solvername;
args [3] = ierr;
mono_runtime_invoke (pISparseSolver_FromXMLFile, NULL, args, NULL);
}
void isparsesolver_fromxmlfile(int* SolverRef,char* File,char* solvername,int* ierr){ISparseSolver_FromXMLFile(SolverRef,File,solvername,ierr);}
void ISPARSESOLVER_FROMXMLFILE(int* SolverRef,char* File,char* solvername,int* ierr){ISparseSolver_FromXMLFile(SolverRef,File,solvername,ierr);}
void isparsesolver_fromxmlfile_(int* SolverRef,char* File,char* solvername,int* ierr){ISparseSolver_FromXMLFile(SolverRef,File,solvername,ierr);}
void ISPARSESOLVER_FROMXMLFILE_(int* SolverRef,char* File,char* solvername,int* ierr){ISparseSolver_FromXMLFile(SolverRef,File,solvername,ierr);}
void _isparsesolver_fromxmlfile(int* SolverRef,char* File,char* solvername,int* ierr){ISparseSolver_FromXMLFile(SolverRef,File,solvername,ierr);}
void _ISPARSESOLVER_FROMXMLFILE(int* SolverRef,char* File,char* solvername,int* ierr){ISparseSolver_FromXMLFile(SolverRef,File,solvername,ierr);}
void _ISparseSolver_FromXMLFile(int* SolverRef,char* File,char* solvername,int* ierr){ISparseSolver_FromXMLFile(SolverRef,File,solvername,ierr);}
void ISparseSolver_FromXMLFile_(int* SolverRef,char* File,char* solvername,int* ierr){ISparseSolver_FromXMLFile(SolverRef,File,solvername,ierr);}
MonoMethod *pISparseSolver_DefineMatrix;
void ISparseSolver_DefineMatrix(int* SolverRef,int* MatrixRef,int* ierr){
void* args[3];
args [0] = SolverRef;
args [1] = MatrixRef;
args [2] = ierr;
mono_runtime_invoke (pISparseSolver_DefineMatrix, NULL, args, NULL);
}
void isparsesolver_definematrix(int* SolverRef,int* MatrixRef,int* ierr){ISparseSolver_DefineMatrix(SolverRef,MatrixRef,ierr);}
void ISPARSESOLVER_DEFINEMATRIX(int* SolverRef,int* MatrixRef,int* ierr){ISparseSolver_DefineMatrix(SolverRef,MatrixRef,ierr);}
void isparsesolver_definematrix_(int* SolverRef,int* MatrixRef,int* ierr){ISparseSolver_DefineMatrix(SolverRef,MatrixRef,ierr);}
void ISPARSESOLVER_DEFINEMATRIX_(int* SolverRef,int* MatrixRef,int* ierr){ISparseSolver_DefineMatrix(SolverRef,MatrixRef,ierr);}
void _isparsesolver_definematrix(int* SolverRef,int* MatrixRef,int* ierr){ISparseSolver_DefineMatrix(SolverRef,MatrixRef,ierr);}
void _ISPARSESOLVER_DEFINEMATRIX(int* SolverRef,int* MatrixRef,int* ierr){ISparseSolver_DefineMatrix(SolverRef,MatrixRef,ierr);}
void _ISparseSolver_DefineMatrix(int* SolverRef,int* MatrixRef,int* ierr){ISparseSolver_DefineMatrix(SolverRef,MatrixRef,ierr);}
void ISparseSolver_DefineMatrix_(int* SolverRef,int* MatrixRef,int* ierr){ISparseSolver_DefineMatrix(SolverRef,MatrixRef,ierr);}
MonoMethod *pISparseSolver_Solve;
void ISparseSolver_Solve(int* SolverRef,int* N,double* x,double* rhs,int* ierr){
void* args[5];
args [0] = SolverRef;
args [1] = N;
args [2] = x;
args [3] = rhs;
args [4] = ierr;
mono_runtime_invoke (pISparseSolver_Solve, NULL, args, NULL);
}
void isparsesolver_solve(int* SolverRef,int* N,double* x,double* rhs,int* ierr){ISparseSolver_Solve(SolverRef,N,x,rhs,ierr);}
void ISPARSESOLVER_SOLVE(int* SolverRef,int* N,double* x,double* rhs,int* ierr){ISparseSolver_Solve(SolverRef,N,x,rhs,ierr);}
void isparsesolver_solve_(int* SolverRef,int* N,double* x,double* rhs,int* ierr){ISparseSolver_Solve(SolverRef,N,x,rhs,ierr);}
void ISPARSESOLVER_SOLVE_(int* SolverRef,int* N,double* x,double* rhs,int* ierr){ISparseSolver_Solve(SolverRef,N,x,rhs,ierr);}
void _isparsesolver_solve(int* SolverRef,int* N,double* x,double* rhs,int* ierr){ISparseSolver_Solve(SolverRef,N,x,rhs,ierr);}
void _ISPARSESOLVER_SOLVE(int* SolverRef,int* N,double* x,double* rhs,int* ierr){ISparseSolver_Solve(SolverRef,N,x,rhs,ierr);}
void _ISparseSolver_Solve(int* SolverRef,int* N,double* x,double* rhs,int* ierr){ISparseSolver_Solve(SolverRef,N,x,rhs,ierr);}
void ISparseSolver_Solve_(int* SolverRef,int* N,double* x,double* rhs,int* ierr){ISparseSolver_Solve(SolverRef,N,x,rhs,ierr);}
MonoMethod *pPartition_GetI0;
void Partition_GetI0(int* _ref,int* i0,int* ierr){
void* args[3];
args [0] = _ref;
args [1] = i0;
args [2] = ierr;
mono_runtime_invoke (pPartition_GetI0, NULL, args, NULL);
}
void partition_geti0(int* _ref,int* i0,int* ierr){Partition_GetI0(_ref,i0,ierr);}
void PARTITION_GETI0(int* _ref,int* i0,int* ierr){Partition_GetI0(_ref,i0,ierr);}
void partition_geti0_(int* _ref,int* i0,int* ierr){Partition_GetI0(_ref,i0,ierr);}
void PARTITION_GETI0_(int* _ref,int* i0,int* ierr){Partition_GetI0(_ref,i0,ierr);}
void _partition_geti0(int* _ref,int* i0,int* ierr){Partition_GetI0(_ref,i0,ierr);}
void _PARTITION_GETI0(int* _ref,int* i0,int* ierr){Partition_GetI0(_ref,i0,ierr);}
void _Partition_GetI0(int* _ref,int* i0,int* ierr){Partition_GetI0(_ref,i0,ierr);}
void Partition_GetI0_(int* _ref,int* i0,int* ierr){Partition_GetI0(_ref,i0,ierr);}
MonoMethod *pPartition_GetLocLen;
void Partition_GetLocLen(int* _ref,int* LocLen,int* ierr){
void* args[3];
args [0] = _ref;
args [1] = LocLen;
args [2] = ierr;
mono_runtime_invoke (pPartition_GetLocLen, NULL, args, NULL);
}
void partition_getloclen(int* _ref,int* LocLen,int* ierr){Partition_GetLocLen(_ref,LocLen,ierr);}
void PARTITION_GETLOCLEN(int* _ref,int* LocLen,int* ierr){Partition_GetLocLen(_ref,LocLen,ierr);}
void partition_getloclen_(int* _ref,int* LocLen,int* ierr){Partition_GetLocLen(_ref,LocLen,ierr);}
void PARTITION_GETLOCLEN_(int* _ref,int* LocLen,int* ierr){Partition_GetLocLen(_ref,LocLen,ierr);}
void _partition_getloclen(int* _ref,int* LocLen,int* ierr){Partition_GetLocLen(_ref,LocLen,ierr);}
void _PARTITION_GETLOCLEN(int* _ref,int* LocLen,int* ierr){Partition_GetLocLen(_ref,LocLen,ierr);}
void _Partition_GetLocLen(int* _ref,int* LocLen,int* ierr){Partition_GetLocLen(_ref,LocLen,ierr);}
void Partition_GetLocLen_(int* _ref,int* LocLen,int* ierr){Partition_GetLocLen(_ref,LocLen,ierr);}
MonoMethod *pPartition_GetMPIrank;
void Partition_GetMPIrank(int* _ref,int* MPIrank,int* ierr){
void* args[3];
args [0] = _ref;
args [1] = MPIrank;
args [2] = ierr;
mono_runtime_invoke (pPartition_GetMPIrank, NULL, args, NULL);
}
void partition_getmpirank(int* _ref,int* MPIrank,int* ierr){Partition_GetMPIrank(_ref,MPIrank,ierr);}
void PARTITION_GETMPIRANK(int* _ref,int* MPIrank,int* ierr){Partition_GetMPIrank(_ref,MPIrank,ierr);}
void partition_getmpirank_(int* _ref,int* MPIrank,int* ierr){Partition_GetMPIrank(_ref,MPIrank,ierr);}
void PARTITION_GETMPIRANK_(int* _ref,int* MPIrank,int* ierr){Partition_GetMPIrank(_ref,MPIrank,ierr);}
void _partition_getmpirank(int* _ref,int* MPIrank,int* ierr){Partition_GetMPIrank(_ref,MPIrank,ierr);}
void _PARTITION_GETMPIRANK(int* _ref,int* MPIrank,int* ierr){Partition_GetMPIrank(_ref,MPIrank,ierr);}
void _Partition_GetMPIrank(int* _ref,int* MPIrank,int* ierr){Partition_GetMPIrank(_ref,MPIrank,ierr);}
void Partition_GetMPIrank_(int* _ref,int* MPIrank,int* ierr){Partition_GetMPIrank(_ref,MPIrank,ierr);}
MonoMethod *pPartition_GetMPIsize;
void Partition_GetMPIsize(int* _ref,int* MPIsize,int* ierr){
void* args[3];
args [0] = _ref;
args [1] = MPIsize;
args [2] = ierr;
mono_runtime_invoke (pPartition_GetMPIsize, NULL, args, NULL);
}
void partition_getmpisize(int* _ref,int* MPIsize,int* ierr){Partition_GetMPIsize(_ref,MPIsize,ierr);}
void PARTITION_GETMPISIZE(int* _ref,int* MPIsize,int* ierr){Partition_GetMPIsize(_ref,MPIsize,ierr);}
void partition_getmpisize_(int* _ref,int* MPIsize,int* ierr){Partition_GetMPIsize(_ref,MPIsize,ierr);}
void PARTITION_GETMPISIZE_(int* _ref,int* MPIsize,int* ierr){Partition_GetMPIsize(_ref,MPIsize,ierr);}
void _partition_getmpisize(int* _ref,int* MPIsize,int* ierr){Partition_GetMPIsize(_ref,MPIsize,ierr);}
void _PARTITION_GETMPISIZE(int* _ref,int* MPIsize,int* ierr){Partition_GetMPIsize(_ref,MPIsize,ierr);}
void _Partition_GetMPIsize(int* _ref,int* MPIsize,int* ierr){Partition_GetMPIsize(_ref,MPIsize,ierr);}
void Partition_GetMPIsize_(int* _ref,int* MPIsize,int* ierr){Partition_GetMPIsize(_ref,MPIsize,ierr);}

void InitBinding() {
MonoClass *klass;
MonoMethodDesc* desc_X;
klass = mono_class_from_name (img, "ilPSP.ExternalBinding", "MsrMatrix_");
assert(klass);
desc_X = mono_method_desc_new ("ilPSP.ExternalBinding.MsrMatrix_:New(int&,int&,int&,int&,int&,int&)", 1);
assert(desc_X);
pMsrMatrix_New = mono_method_desc_search_in_class (desc_X, klass);
assert(pMsrMatrix_New);
klass = mono_class_from_name (img, "ilPSP.ExternalBinding", "IMutableMatrix_");
assert(klass);
desc_X = mono_method_desc_new ("ilPSP.ExternalBinding.IMutableMatrix_:SetEntry(int&,int&,int&,double&,int&)", 1);
assert(desc_X);
pIMutableMatrix_SetEntry = mono_method_desc_search_in_class (desc_X, klass);
assert(pIMutableMatrix_SetEntry);
klass = mono_class_from_name (img, "ilPSP.ExternalBinding", "Common_");
assert(klass);
desc_X = mono_method_desc_new ("ilPSP.ExternalBinding.Common_:ReleaseObject(int&,int&)", 1);
assert(desc_X);
pCommon_ReleaseObject = mono_method_desc_search_in_class (desc_X, klass);
assert(pCommon_ReleaseObject);
desc_X = mono_method_desc_new ("ilPSP.ExternalBinding.Common_:Test(int&,int&)", 1);
assert(desc_X);
pCommon_Test = mono_method_desc_search_in_class (desc_X, klass);
assert(pCommon_Test);
desc_X = mono_method_desc_new ("ilPSP.ExternalBinding.Common_:ilPSPInitialize()", 1);
assert(desc_X);
pCommon_ilPSPInitialize = mono_method_desc_search_in_class (desc_X, klass);
assert(pCommon_ilPSPInitialize);
desc_X = mono_method_desc_new ("ilPSP.ExternalBinding.Common_:ilPSPFinalize()", 1);
assert(desc_X);
pCommon_ilPSPFinalize = mono_method_desc_search_in_class (desc_X, klass);
assert(pCommon_ilPSPFinalize);
klass = mono_class_from_name (img, "ilPSP.ExternalBinding", "IMutableMatrixEx_");
assert(klass);
desc_X = mono_method_desc_new ("ilPSP.ExternalBinding.IMutableMatrixEx_:SaveToTextFileSparse(int&,byte*,int&)", 1);
assert(desc_X);
pIMutableMatrixEx_SaveToTextFileSparse = mono_method_desc_search_in_class (desc_X, klass);
assert(pIMutableMatrixEx_SaveToTextFileSparse);
desc_X = mono_method_desc_new ("ilPSP.ExternalBinding.IMutableMatrixEx_:SaveToTextFileSparseF(int&,byte*,byte*,int&)", 1);
assert(desc_X);
pIMutableMatrixEx_SaveToTextFileSparseF = mono_method_desc_search_in_class (desc_X, klass);
assert(pIMutableMatrixEx_SaveToTextFileSparseF);
klass = mono_class_from_name (img, "ilPSP.ExternalBinding", "ISparseMatrix_");
assert(klass);
desc_X = mono_method_desc_new ("ilPSP.ExternalBinding.ISparseMatrix_:GetI0(int&,int&,int&)", 1);
assert(desc_X);
pISparseMatrix_GetI0 = mono_method_desc_search_in_class (desc_X, klass);
assert(pISparseMatrix_GetI0);
desc_X = mono_method_desc_new ("ilPSP.ExternalBinding.ISparseMatrix_:GetLocLen(int&,int&,int&)", 1);
assert(desc_X);
pISparseMatrix_GetLocLen = mono_method_desc_search_in_class (desc_X, klass);
assert(pISparseMatrix_GetLocLen);
desc_X = mono_method_desc_new ("ilPSP.ExternalBinding.ISparseMatrix_:GetRowPart(int&,int&,int&)", 1);
assert(desc_X);
pISparseMatrix_GetRowPart = mono_method_desc_search_in_class (desc_X, klass);
assert(pISparseMatrix_GetRowPart);
klass = mono_class_from_name (img, "ilPSP.ExternalBinding", "ISparseSolver_");
assert(klass);
desc_X = mono_method_desc_new ("ilPSP.ExternalBinding.ISparseSolver_:FromXML(int&,byte*,int&)", 1);
assert(desc_X);
pISparseSolver_FromXML = mono_method_desc_search_in_class (desc_X, klass);
assert(pISparseSolver_FromXML);
desc_X = mono_method_desc_new ("ilPSP.ExternalBinding.ISparseSolver_:FromXMLBegin(byte*,int&)", 1);
assert(desc_X);
pISparseSolver_FromXMLBegin = mono_method_desc_search_in_class (desc_X, klass);
assert(pISparseSolver_FromXMLBegin);
desc_X = mono_method_desc_new ("ilPSP.ExternalBinding.ISparseSolver_:FromXMLSubmit(byte*,int&)", 1);
assert(desc_X);
pISparseSolver_FromXMLSubmit = mono_method_desc_search_in_class (desc_X, klass);
assert(pISparseSolver_FromXMLSubmit);
desc_X = mono_method_desc_new ("ilPSP.ExternalBinding.ISparseSolver_:FromXMLEnd(int&,int&)", 1);
assert(desc_X);
pISparseSolver_FromXMLEnd = mono_method_desc_search_in_class (desc_X, klass);
assert(pISparseSolver_FromXMLEnd);
desc_X = mono_method_desc_new ("ilPSP.ExternalBinding.ISparseSolver_:FromXMLFileF(int&,byte*,byte*,byte*,int&)", 1);
assert(desc_X);
pISparseSolver_FromXMLFileF = mono_method_desc_search_in_class (desc_X, klass);
assert(pISparseSolver_FromXMLFileF);
desc_X = mono_method_desc_new ("ilPSP.ExternalBinding.ISparseSolver_:FromXMLFile(int&,byte*,byte*,int&)", 1);
assert(desc_X);
pISparseSolver_FromXMLFile = mono_method_desc_search_in_class (desc_X, klass);
assert(pISparseSolver_FromXMLFile);
desc_X = mono_method_desc_new ("ilPSP.ExternalBinding.ISparseSolver_:DefineMatrix(int&,int&,int&)", 1);
assert(desc_X);
pISparseSolver_DefineMatrix = mono_method_desc_search_in_class (desc_X, klass);
assert(pISparseSolver_DefineMatrix);
desc_X = mono_method_desc_new ("ilPSP.ExternalBinding.ISparseSolver_:Solve(int&,int&,double*,double*,int&)", 1);
assert(desc_X);
pISparseSolver_Solve = mono_method_desc_search_in_class (desc_X, klass);
assert(pISparseSolver_Solve);
klass = mono_class_from_name (img, "ilPSP.ExternalBinding", "Partition_");
assert(klass);
desc_X = mono_method_desc_new ("ilPSP.ExternalBinding.Partition_:GetI0(int&,int&,int&)", 1);
assert(desc_X);
pPartition_GetI0 = mono_method_desc_search_in_class (desc_X, klass);
assert(pPartition_GetI0);
desc_X = mono_method_desc_new ("ilPSP.ExternalBinding.Partition_:GetLocLen(int&,int&,int&)", 1);
assert(desc_X);
pPartition_GetLocLen = mono_method_desc_search_in_class (desc_X, klass);
assert(pPartition_GetLocLen);
desc_X = mono_method_desc_new ("ilPSP.ExternalBinding.Partition_:GetMPIrank(int&,int&,int&)", 1);
assert(desc_X);
pPartition_GetMPIrank = mono_method_desc_search_in_class (desc_X, klass);
assert(pPartition_GetMPIrank);
desc_X = mono_method_desc_new ("ilPSP.ExternalBinding.Partition_:GetMPIsize(int&,int&,int&)", 1);
assert(desc_X);
pPartition_GetMPIsize = mono_method_desc_search_in_class (desc_X, klass);
assert(pPartition_GetMPIsize);
}


