#
#  This file is part of MUMPS 5.0.2, released
#  on Fri Jul 15 09:12:54 UTC 2016
#
# We are grateful to Evgenii Rudnyi for his help and suggestions
# regarding Windows installation.
#Begin orderings

# NOTE that PORD is distributed within MUMPS by default. If you would like to
# use other orderings, you need to obtain the corresponding package and modify
# the variables below accordingly.
# For example, to have Metis available within MUMPS:
#          1/ download Metis and compile it
#          2/ uncomment (suppress # in first column) lines
#             starting with LMETISDIR,  LMETIS, PATHMETIS
#          3/ add -Dmetis in line ORDERINGSF
#             ORDERINGSF  = -Dpord -Dmetis
#          4/ Compile and install MUMPS
#             make clean; make   (to clean up previous installation)
#
#          Metis/ParMetis and SCOTCH/PT-SCOTCH (ver 6.0 and later) orderings are now available for MUMPS.
#

#SCOTCHDIR  = ${HOME}/scotch_6.0
#PATHSCOTCH = -LIBPATH:$(SCOTCHDIR)/lib
#ISCOTCH    = -I$(SCOTCHDIR)/include  # only needed for pt-scotch
# You have to choose one among the following two lines depending on
# the type of analysis you want to perform. If you want to perform only
# sequential analysis choose the first (remember to add -Dscotch in the ORDERINGSF
# variable below); for both parallel and sequential analysis choose the second 
# line (remember to add -Dptscotch in the ORDERINGSF variable below)

#LSCOTCH    = libscotch.lib libscotcherr.lib libesmumps.lib
#LSCOTCH    = libptscotch.lib libptscotcherr.lib libptesmumps.lib libscotch.lib


LPORDDIR = $(topdir)/PORD/lib/
IPORD    = -I$(topdir)/PORD/include/
PATHPORD = /LIBPATH:$(LPORDDIR)
LPORD    = libpord.lib

#LMETISDIR = /local/metis/
#PATHMETIS = -LIBPATH:$(PATHMETIS)
#IMETIS    = # should be provided if you use parmetis, to access parmetis.h

# You have to choose one among the following two lines depending on
# the type of analysis you want to perform. If you want to perform only
# sequential analysis choose the first (remember to add -Dmetis in the ORDERINGSF
# variable below); for both parallel and sequential analysis choose the second 
# line (remember to add -Dparmetis in the ORDERINGSF variable below)

#LMETIS    = libmetis.lib
#LMETIS    = libparmetis.lib libmetis.lib

# The following variables will be used in the compilation process.
# Please note that -Dptscotch and -Dparmetis imply -Dscotch and -Dmetis respectively.
#ORDERINGSF = -Dscotch -Dmetis -Dpord -Dptscotch -Dparmetis
ORDERINGSF  = -Dpord
ORDERINGSC  = $(ORDERINGSF)

PATHORDERINGS = $(PATHMETIS) $(PATHPORD) $(PATHSCOTCH)
LORDERINGS = $(LMETIS) $(LPORD) $(LSCOTCH)
IORDERINGSF = $(ISCOTCH)
IORDERINGSC = $(IMETIS) $(IPORD) $(ISCOTCH)

# For Windows
#End orderings
########################################################################
########################################################################
################################################################################

PLAT    =
LIBEXT  = .lib
OUTC    = -Fo
OUTF    = -Fo
RM = /bin/rm -f
CC = cl
FC = ifort
FL = ifort
AR = lib -out:
#RANLIB = ranlib
RANLIB  = echo
INCSEQ = -I$(topdir)/libseq
LIBSEQ = $(topdir)/libseq/libmpiseq.lib

INCPAR = -I"C:\Program Files\Microsoft MPI\Inc" -I"C:\Program Files\Microsoft MPI\Inc\amd64"
LIBPAR = msmpi.lib msmpifec.lib mkl_scalapack_lp64.lib mkl_blacs_msmpi_lp64.lib 

#LIBBLAS = -L/usr/lib/xmm/ -lf77blas -latlas
#LIBBLAS = -L/local/BLAS -lblas
LIBBLAS = mkl_intel_thread.lib mkl_core.lib libiomp5md.lib mkl_intel_lp64.lib 
#LIBOTHERS = -lpthread
LIBOTHERS = -link $(PATHORDERINGS) -link /LIBPATH:"C:\Program Files\Microsoft MPI\Lib\amd64"
#Preprocessor defs for calling Fortran from C (-DAdd_ or -DAdd__ or -DUPPER)
CDEFS   = -DUPPER

#Begin Optimized options
#OPTF    = -O -MD -Dintel_ -DALLOW_NON_INIT -fpp
OPTF    = -O -MD -Dintel_ -DALLOW_NON_INIT -fpp
OPTL    = 
OPTC    = -O -MD
#End Optimized options
#INCS = $(INCSEQ)
#LIBS = $(LIBSEQ)
INCS = $(INCPAR)
LIBS = $(LIBPAR)
LIBSEQNEEDED = 
