#
# This is the Gitlab CI file for the public repository.
# Its main purpose is to define a pipeline which
# publishes the BoSSS tutorials and other Jupyter sheets as static pages.
#


stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: 
    - dotnet build ./src/Public.sln -c Release -v q # build the project
  tags:
    - C#7.0
    - big_server
  artifacts:
    paths:
#      - src/L4-application/TutorialTests/bin/Release/net6.0
      - src/L4-application/PublicTestRunner/bin/Release/net6.0
    expire_in: 2 days
    
test:
  stage: test
  before_script:
    - cd src/L4-application/PublicTestRunner
    - dir 
    - cd bin/Release/net6.0
#    - cd src/L4-application/PublicTestRunner/bin/Release/net6.0
#    - bash -c "chmod +x PublicTestRunner.exe"
  tags:
    - C#7.0
    - big_server    
  script:
    -  dir PublicTestRunner*
    - ./PublicTestRunner.exe nunit3 TutorialTests --result=result.xml    
  dependencies:
    - build
  needs:
    - build  
  artifacts:
    reports:
      junit: public/src/L4-application/PublicTestRunner/bin/Release/net6.0/result.xml
    paths:
      - src/L4-application/PublicTestRunner/bin/Release/net6.0/*.html
    expire_in: 2 days
    

# ============================================================
# Publication of the TutorialTests HTML output on Gitlab pages
# ============================================================
#
# Remarks:
# (1) It seems to be very important that the directory is named 'public';
#     Otherwise, I always got a 404 error on the pages site.
# (2) the 'generate-index.py' script is used to generate a raw index file.
#
pages:
  stage: deploy
  needs:
    - build
    - test
  script:
    - dir src/L4-application/PublicTestRunner/bin/Release/net6.0/*.html
    - ./downloadValidationTestsWrapper.bat
    - cd public  
    - dir
    - python ../doc/Generate-Index-Files-1.0/generate-index.py
    - dir 
  artifacts:
    paths:
      - public/
  only:
# replace by master  
    - master
  tags:
    - C#7.0
    - big_server