//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoSSS.Application.ExternalBinding.CodeGen {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoSSS.Application.ExternalBinding.CodeGen.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ORIGIN_PATH=/mnt/c/Users/florian/Documents/BoSSS-master/public/src/L4-application/ExternalBinding.CodeGen/bin/Debug
        ///#rm -r ./managed/*
        ///#cp $ORIGIN_PATH/{*.dll,*.exe} ./managed/
        ///rm *.o
        ///
        ///SourceFiles=$(ls *.cpp)
        ///
        ///for SourceFile in $SourceFiles; do
        ///    g++ -c $SourceFile  `pkg-config --cflags --libs mono-2`
        ///done
        ///g++ *.o `pkg-config --cflags --libs mono-2` -o ExtBindingTest.out .
        /// </summary>
        internal static string compile_sh {
            get {
                return ResourceManager.GetString("compile_sh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // ExtBindingTest.cpp : This file contains the &apos;main&apos; function. Program execution begins and ends there.
        /////
        ///
        ///#include &lt;stdlib.h&gt;
        ///#include &lt;stdio.h&gt;
        ///#include &lt;assert.h&gt;
        ///
        ///#include &quot;BoSSScpp.h&quot;
        ///
        ///using namespace BoSSS::Application::ExternalBinding;
        ///using namespace BoSSS::Foundation::Grid;
        ///using namespace BoSSS::Foundation::Grid::Classic;
        ///
        ///void InitMeshTest() {
        ///    int nCells = 9;
        ///
        ///    
        ///    int __faces[][4] = {
        ///     {1, 5, 21, 17},
        ///     {4, 20, 21, 5},
        ///     {2, 6, 22, 18},
        ///     {5, 21, 22, 6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExtBindingTest_cpp {
            get {
                return ResourceManager.GetString("ExtBindingTest_cpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include &lt;stdlib.h&gt;
        ///#include &lt;assert.h&gt;
        ///
        ///#include &lt;mono/metadata/mono-config.h&gt;
        ///#include &lt;mono/jit/jit.h&gt;
        ///#include &lt;mono/metadata/assembly.h&gt;
        ///#include &lt;mono/metadata/debug-helpers.h&gt;
        ///
        ///#include &quot;MonoBoSSSglobals.h&quot;
        ///
        ///
        ///
        ///namespace BoSSS
        ///{
        ///    
        ///    
        ///}
        ///.
        /// </summary>
        internal static string MonoBoSSSglobals_cpp {
            get {
                return ResourceManager.GetString("MonoBoSSSglobals_cpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #pragma once
        ///namespace BoSSS
        ///{
        ///class MonoBoSSSglobals
        ///{
        ///};
        ///}
        ///.
        /// </summary>
        internal static string MonoBoSSSglobals_h {
            get {
                return ResourceManager.GetString("MonoBoSSSglobals_h", resourceCulture);
            }
        }
    }
}
