clc
clear all

% create figure 11 in Pressure and shear flow singularities: fluid splitting and printing nip hydrodynamics
% Matthias Elia Rieckmann, Pauline Brumm, Hans Martin Sauer, Edgar Doersam, Florian Kummer
% Physics of Fluids, 2023

opts = detectImportOptions('PrintingNip-Part4.csv');
% preview('PrintingNip-Part4.csv', opts)
dat = readtable('PrintingNip-Part4.csv', opts);
dat = dat(~isnan(dat.dPdXatStagnationPoint),:);
uVals = sort(unique(dat.id_V_Wall));
xVals = sort(unique(dat.id_X_Stag));

uVals = uVals(2:end-1);
xVals = xVals(2:end-1);

[A, B] = meshgrid(uVals,xVals);
C = zeros(size(A));
for i=1:size(A,1)
    for j=1:size(A,2)
        t = dat(dat.id_V_Wall == A(i,j) & dat.id_X_Stag == B(i,j),'dPdXatStagnationPoint');
        C(i,j) = t.dPdXatStagnationPoint;
    end
end

dat2 = importdata('ExperimentalResults.txt');
dat2 = dat2.data;

s = 0.027;
e = 0.0395;
UExp = dat2(:,2);
PExp = 16.*dat2(:,3)*100.*dat2(:,3)*100.*s;
XExp = sqrt(sqrt(UExp.*8.*e./PExp) .* 0.1);

U = dat.id_V_Wall;
X = dat.id_X_Stag;
P = dat.dPdXatStagnationPoint;

idx = ~isnan(P);
U = U(idx);
X = X(idx);
P = P(idx);

PlotMap(A,B,C,UExp,XExp,PExp);
set(gcf,'Position',[10 10 1000 800]);
h = gcf;
% exportgraphics(h,'UXPMap.pdf','ContentType','image','Resolution',120)
% scatter3(U,X,P); hold on;
% surf(A,B,C);
% set(gca,'Xscale','log','Zscale','log','Yscale','log')
% xlabel('$u \, \left[\frac{m}{s}\right]$','Interpreter','latex')
% ylabel('$x_m \, \left[m\right]$','Interpreter','latex')
% zlabel('$\frac{\partial p}{\partial x} \, \left[\frac{N}{m^3}\right]$','Interpreter','latex')
% scatter3(UExp,XExp,PExp);
% legend('Simulation', '', 'Experiment')
% 
% hold off;

function PlotMap(xdata1, ydata1, zdata1, X2, Y2, Z2)
    %CREATEFIGURE(X1, Y1, Z1, S1, C1, xdata1, ydata1, zdata1, X2, Y2, Z2, C2)
    %  X1:  scatter3 x
    %  Y1:  scatter3 y
    %  Z1:  scatter3 z
    %  S1:  scatter3 s
    %  C1:  scatter3 c
    %  XDATA1:  surface xdata
    %  YDATA1:  surface ydata
    %  ZDATA1:  surface zdata
    %  X2:  scatter3 x
    %  Y2:  scatter3 y
    %  Z2:  scatter3 z
    %  C2:  scatter3 c

    %  Auto-generated by MATLAB on 28-Jun-2022 21:24:22

    % Create figure
    figure1 = figure;

    % Create axes
    axes1 = axes('Parent',figure1);
    hold(axes1,'on');

    % Create surf
    surf(xdata1,ydata1,zdata1,'DisplayName','Simulation','Parent',axes1,...
        'MarkerFaceColor',[0.850980401039124 0.325490206480026 0.0980392172932625],...
        'MarkerEdgeColor','none',...
        'MarkerSize',8,...
        'Marker','o',...
        'LineStyle','--',...
        'FaceColor',[0.800000011920929 0.800000011920929 0.800000011920929]);

    % Create scatter3
    scatter3(X2,Y2,Z2,'DisplayName','Experiment','LineWidth',3,...
        'Marker','square');

    % Create zlabel
    zlabel('$\frac{\partial p}{\partial x} \, \left[\frac{N}{m^3}\right]$',...
        'Interpreter','latex');

    % Create ylabel
    ylabel('$x_m \, \left[m\right]$','Interpreter','latex');

    % Create xlabel
    xlabel('$u \, \left[\frac{m}{s}\right]$','Interpreter','latex');

    view(axes1,[-70.6037109375001 15.654718798151]);
    grid(axes1,'on');
    hold(axes1,'off');
    % Set the remaining axes properties
    set(axes1,'FontSize',20,'OuterPosition',[0.13 0 0.775 0.9075],'XMinorTick',...
        'on','XScale','log','YMinorTick','on','YScale','log','ZMinorTick','on',...
        'ZScale','log');
    % Create legend
    legend1 = legend(axes1,'show');
    set(legend1,...
        'Position',[0.46715748823633 0.834166775403636 0.101466273527341 0.0929791245051079]);

end