//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoSSS.Foundation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoSSS.Foundation.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xeoAAARRdWFkcnVsZXMAteoAAAMwAEYAAAAQSXRlbTEAAQAAAARJdGVtMgAYAAAABDAAEAAAAAEwAAAAAAAAAAAAAAAESXRlbTMAEAAAAAEwAAAAAAAAAABAAAADMQBUAQAAEEl0ZW0xABMAAAAESXRlbTIAwwAAAAQwABAAAAABMADa8ioGPirvvwAEMQAQAAAAATAA97KcXpmu678ABDIAEAAAAAEwAJThjSK5veW/AAQzABAAAAABMADYagEJwLzbvwAENAAQAAAAATAAcuKReFAOw78ABDUAEAAAAAEwAHLikXhQDsM/AAQ2ABAAAAABMADYagEJwLzbPwAENwAQAAAAATAAlOGNIrm95T8ABDgAEAAAAAEwAPeynF6Zrus/AAQ5ABAAAAABMADa8ioGPirvPwAABEl0ZW0zAHMAAAABMAAc3GKLXxGxPwExAPTveMg4IcM/ATIAMLwAnQULzD8BMwD4m1V6qjvRPwE0APHWFHDe6dI/ATUA8dYU [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LineQuadRules_bin {
            get {
                return ResourceManager.GetString("LineQuadRules_bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FZwbAARRdWFkcnVsZXMABZwbAAMwAFwAAAAQSXRlbTEAAQAAAARJdGVtMgAuAAAABDAAJgAAAAEwAAAAAAAAAAAAATEAAAAAAAAAAAABMgAAAAAAAAAAAAAABEl0ZW0zABAAAAABMACB7tHxizn3PwAAAzEA+AAAABBJdGVtMQABAAAABEl0ZW0yAKkAAAAEMAAmAAAAATAA2PbUolSG4L8BMQCSnirZwxTTvwEyAGthYNgZ/Mq/AAQxACYAAAABMAAAAAAAAAAAAAExAAAAAAAAAAAAATIAEElIYhM95D8ABDIAJgAAAAEwAAAAAAAAAAAAATEAkp4q2cMU4z8BMgBrYWDYGfzKvwAEMwAmAAAAATAA2PbUolSG4D8BMQCSnirZwxTTvwEyAGthYNgZ/Mq/AAAESXRlbTMAMQAAAAEwAHju0fGLOdc/ATEAeO7R8Ys51z8BMgB47tHxiznXPwEzAHju0fGLOdc/AAADMgAsAQAAEEl0ZW0xAAIAAAAE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TetraQuadRules_bin {
            get {
                return ResourceManager.GetString("TetraQuadRules_bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t+8BAARRdWFkcnVsZXMAp+8BAAMwAFEAAAAQSXRlbTEAAQAAAARJdGVtMgAjAAAABDAAGwAAAAEwAAAAAAAAAAAAATEAVVVVVVVV1T8AAARJdGVtMwAQAAAAATAAHDOQRad5AkAAAAMxAMwAAAAQSXRlbTEAAwAAAARJdGVtMgB9AAAABDAAGwAAAAEwALS72sE30+C/ATEAxyGWa/I7z78ABDEAGwAAAAEwALS72sE30+A/ATEAxyGWa/I7z78ABDIAGwAAAAEwAIVm6k12CMK/ATEAx9068FEk7T8ABDMAGwAAAAEwAIVm6k12CMI/ATEAx9068FEk7T8AAARJdGVtMwAxAAAAATAAx9068FEk7T8BMQDH3TrwUSTtPwEyAMchlmvyO88/ATMAxyGWa/I7zz8AAAMyAJkBAAAQSXRlbTEABQAAAARJdGVtMgATAQAABDAAGwAAAAEwAP57NqZdZem/ATEAOo8pk6g93L8ABDEAGwAAAAEwAAAAAAAA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TriangleQuadRules_bin {
            get {
                return ResourceManager.GetString("TriangleQuadRules_bin", resourceCulture);
            }
        }
    }
}
